[[profile]]
name = "Daheim"

[[profile.output]]
enable = false
search = ["m=0x0A5F", "s=", "v=BOE"]

[[profile.output]]
enable = true
search = ["m=DELL U2723QE", "s=2ZFGH34", "v=Dell Inc."]
mode = "3840x2160@59.997Hz"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile]]
name = "Standalone"

[[profile.output]]
enable = true
search = ["m=0x0A5F", "s=", "v=BOE"]
mode = "1920x1200@60Hz"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile]]
name = "Beamer"

[[profile.output]]
enable = true
search = ["m=BenQ PJ", "s=0x00000001", "v=BNQ"]
mode = "1920x1080@60Hz"
position = "1920,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = false
search = ["m=0x0A5F", "s=", "v=BOE"]
mode = "1920x1200@60Hz"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

